<?php

namespace AppBundle\Repository;

/**
 * CookingJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookingJobRepository extends \Doctrine\ORM\EntityRepository
{
}
